<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
	<LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<PackageId>CaptchaN.Drawing.ImageSharp</PackageId>
	<Title>CaptchaN.Drawing.ImageSharp</Title>
	<Authors>LeaFrock</Authors>
	<Version>4.1.0</Version>
	<Product>CaptchaN</Product>
	<Description>Draw Captcha based on ImageSharp.</Description>
	<Copyright>Copyright © LeaFrock 2026</Copyright>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageTags>captcha;imagesharp;leaflib</PackageTags>
	<PackageProjectUrl>https://github.com/LeaFrock/CaptchaN</PackageProjectUrl>
	<RepositoryUrl>https://github.com/LeaFrock/CaptchaN.git</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<PackageReleaseNotes>Bump ImageSharp to v4</PackageReleaseNotes>
	<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageIcon>leaf.png</PackageIcon>
	<SixLaborsLicenseFile>sixlabors.lic</SixLaborsLicenseFile>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Condition="'$(TargetFramework)' == 'net8.0'" Include="Microsoft.Extensions.Options.DataAnnotations" Version="8.*" />
	<PackageReference Condition="'$(TargetFramework)' == 'net10.0'" Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.*" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CaptchaN.Abstractions\CaptchaN.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
  	<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	<None Include="..\..\leaf.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
